language: csharp
mono: 
  - latest
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
  - dnvm restore
script:
  - dnx ./Kontur.Tracing.Tests/project.json test --where="cat != Functional"